{
    "containers": {
        "cna": {
            "affected": [
                {
                    "defaultStatus": "unknown",
                    "product": "openvpn",
                    "vendor": "OpenVPN Technologies, Inc",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "2.3.12 and newer"
                        }
                    ]
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "value": "OpenVPN version 2.3.12 and newer is vulnerable to unauthenticated Denial of Service of server via received large control packet. Note that this issue is fixed in 2.3.15 and 2.4.2."
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "cweId": "CWE-617",
                            "description": "CWE-617",
                            "lang": "en",
                            "type": "CWE"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2022-01-13T00:00:00",
                "orgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
                "shortName": "redhat"
            },
            "references": [
                {
                    "name": "41993",
                    "url": "https://www.exploit-db.com/exploits/41993/",
                    "x_refsource": "EXPLOIT-DB"
                },
                {
                    "name": "https://community.openvpn.net/openvpn/wiki/QuarkslabAndCryptographyEngineerAudits",
                    "url": "https://community.openvpn.net/openvpn/wiki/QuarkslabAndCryptographyEngineerAudits",
                    "x_refsource": "CONFIRM"
                },
                {
                    "name": "1038473",
                    "url": "http://www.securitytracker.com/id/1038473",
                    "x_refsource": "SECTRACK"
                },
                {
                    "name": "98444",
                    "url": "http://www.securityfocus.com/bid/98444",
                    "x_refsource": "BID"
                }
            ],
            "x_legacyV4Record": {
                "CVE_data_meta": {
                    "ASSIGNER": "secalert@redhat.com",
                    "ID": "CVE-2017-7478",
                    "STATE": "PUBLIC"
                },
                "affects": {
                    "vendor": {
                        "vendor_data": [
                            {
                                "product": {
                                    "product_data": [
                                        {
                                            "product_name": "openvpn",
                                            "version": {
                                                "version_data": [
                                                    {
                                                        "version_value": "2.3.12 and newer"
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                },
                                "vendor_name": "OpenVPN Technologies, Inc"
                            }
                        ]
                    }
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "eng",
                            "value": "OpenVPN version 2.3.12 and newer is vulnerable to unauthenticated Denial of Service of server via received large control packet. Note that this issue is fixed in 2.3.15 and 2.4.2."
                        }
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "eng",
                                    "value": "CWE-617"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "41993",
                            "refsource": "EXPLOIT-DB",
                            "url": "https://www.exploit-db.com/exploits/41993/"
                        },
                        {
                            "name": "https://community.openvpn.net/openvpn/wiki/QuarkslabAndCryptographyEngineerAudits",
                            "refsource": "CONFIRM",
                            "url": "https://community.openvpn.net/openvpn/wiki/QuarkslabAndCryptographyEngineerAudits"
                        },
                        {
                            "name": "1038473",
                            "refsource": "SECTRACK",
                            "url": "http://www.securitytracker.com/id/1038473"
                        },
                        {
                            "name": "98444",
                            "refsource": "BID",
                            "url": "http://www.securityfocus.com/bid/98444"
                        }
                    ]
                }
            }
        }
    },
    "cveMetadata": {
        "assignerOrgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
        "assignerShortName": "redhat",
        "cveId": "CVE-2017-7478",
        "dateUpdated": "2022-01-13T00:00:00",
        "state": "PUBLISHED"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0"
}