{
    "containers": {
        "cna": {
            "affected": [
                {
                    "defaultStatus": "unknown",
                    "product": "DataPower Gateway",
                    "vendor": "IBM",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "2018.4.1.0"
                        },
                        {
                            "status": "affected",
                            "version": "2018.4.1.12"
                        }
                    ]
                }
            ],
            "datePublished": "2020-09-18T00:00:00",
            "descriptions": [
                {
                    "lang": "en",
                    "value": "IBM DataPower Gateway 2018.4.1.0 through 2018.4.1.12 could allow a remote attacker to cause a denial of service by sending a specially crafted a JSON request with invalid characters. IBM X-Force ID: 184439."
                }
            ],
            "metrics": [
                {
                    "cvssV3_0": {
                        "BM": {
                            "A": "H",
                            "AC": "L",
                            "AV": "N",
                            "C": "N",
                            "I": "N",
                            "PR": "N",
                            "S": "U",
                            "SCORE": "7.500",
                            "UI": "N"
                        },
                        "TM": {
                            "E": "U",
                            "RC": "C",
                            "RL": "O"
                        }
                    }
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "description": "Denial of Service",
                            "lang": "en",
                            "type": "text"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2022-01-13T00:00:00",
                "orgId": "9a959283-ebb5-44b6-b705-dcc2bbced522",
                "shortName": "ibm"
            },
            "references": [
                {
                    "name": "https://www.ibm.com/support/pages/node/6334705",
                    "url": "https://www.ibm.com/support/pages/node/6334705",
                    "x_refsource": "CONFIRM"
                },
                {
                    "name": "ibm-datapower-cve20204580-dos (184439)",
                    "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/184439",
                    "x_refsource": "XF"
                }
            ],
            "x_legacyV4Record": {
                "CVE_data_meta": {
                    "ASSIGNER": "psirt@us.ibm.com",
                    "DATE_PUBLIC": "2020-09-18T00:00:00",
                    "ID": "CVE-2020-4580",
                    "STATE": "PUBLIC"
                },
                "affects": {
                    "vendor": {
                        "vendor_data": [
                            {
                                "product": {
                                    "product_data": [
                                        {
                                            "product_name": "DataPower Gateway",
                                            "version": {
                                                "version_data": [
                                                    {
                                                        "version_value": "2018.4.1.0"
                                                    },
                                                    {
                                                        "version_value": "2018.4.1.12"
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                },
                                "vendor_name": "IBM"
                            }
                        ]
                    }
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "eng",
                            "value": "IBM DataPower Gateway 2018.4.1.0 through 2018.4.1.12 could allow a remote attacker to cause a denial of service by sending a specially crafted a JSON request with invalid characters. IBM X-Force ID: 184439."
                        }
                    ]
                },
                "impact": {
                    "cvssv3": {
                        "BM": {
                            "A": "H",
                            "AC": "L",
                            "AV": "N",
                            "C": "N",
                            "I": "N",
                            "PR": "N",
                            "S": "U",
                            "SCORE": "7.500",
                            "UI": "N"
                        },
                        "TM": {
                            "E": "U",
                            "RC": "C",
                            "RL": "O"
                        }
                    }
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "eng",
                                    "value": "Denial of Service"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "https://www.ibm.com/support/pages/node/6334705",
                            "refsource": "CONFIRM",
                            "title": "IBM Security Bulletin 6334705 (DataPower Gateway)",
                            "url": "https://www.ibm.com/support/pages/node/6334705"
                        },
                        {
                            "name": "ibm-datapower-cve20204580-dos (184439)",
                            "refsource": "XF",
                            "title": "X-Force Vulnerability Report",
                            "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/184439"
                        }
                    ]
                }
            }
        }
    },
    "cveMetadata": {
        "assignerOrgId": "9a959283-ebb5-44b6-b705-dcc2bbced522",
        "assignerShortName": "ibm",
        "cveId": "CVE-2020-4580",
        "datePublished": "2020-09-18T00:00:00",
        "dateUpdated": "2022-01-13T00:00:00",
        "state": "PUBLISHED"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0",
    "x_ValidationErrors": [
        "$ -- validator = oneOf"
    ]
}