{
    "containers": {
        "cna": {
            "affected": [
                {
                    "defaultStatus": "unknown",
                    "product": "n/a",
                    "vendor": "n/a",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "n/a"
                        }
                    ]
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "value": "Python 2.7 through 2.7.17, 3.5 through 3.5.9, 3.6 through 3.6.10, 3.7 through 3.7.6, and 3.8 through 3.8.1 allows an HTTP server to conduct Regular Expression Denial of Service (ReDoS) attacks against a client because of urllib.request.AbstractBasicAuthHandler catastrophic backtracking."
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "description": "n/a",
                            "lang": "en",
                            "type": "text"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2022-01-27T00:00:00",
                "orgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
                "shortName": "mitre"
            },
            "references": [
                {
                    "name": "https://bugs.python.org/issue39503",
                    "url": "https://bugs.python.org/issue39503",
                    "x_refsource": "MISC"
                },
                {
                    "name": "https://python-security.readthedocs.io/vuln/urllib-basic-auth-regex.html",
                    "url": "https://python-security.readthedocs.io/vuln/urllib-basic-auth-regex.html",
                    "x_refsource": "MISC"
                },
                {
                    "name": "https://github.com/python/cpython/pull/18284",
                    "url": "https://github.com/python/cpython/pull/18284",
                    "x_refsource": "MISC"
                },
                {
                    "name": "https://security.netapp.com/advisory/ntap-20200221-0001/",
                    "url": "https://security.netapp.com/advisory/ntap-20200221-0001/",
                    "x_refsource": "CONFIRM"
                },
                {
                    "name": "openSUSE-SU-2020:0274",
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2020-03/msg00003.html",
                    "x_refsource": "SUSE"
                },
                {
                    "name": "USN-4333-1",
                    "url": "https://usn.ubuntu.com/4333-1/",
                    "x_refsource": "UBUNTU"
                },
                {
                    "name": "USN-4333-2",
                    "url": "https://usn.ubuntu.com/4333-2/",
                    "x_refsource": "UBUNTU"
                },
                {
                    "name": "GLSA-202005-09",
                    "url": "https://security.gentoo.org/glsa/202005-09",
                    "x_refsource": "GENTOO"
                },
                {
                    "name": "FEDORA-2020-98e0f0f11b",
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/APGWEMYZIY5VHLCSZ3HD67PA5Z2UQFGH/",
                    "x_refsource": "FEDORA"
                },
                {
                    "name": "FEDORA-2020-6a88dad4a0",
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/7WOKDEXLYW5UQ4S7PA7E37IITOC7C56J/",
                    "x_refsource": "FEDORA"
                },
                {
                    "name": "FEDORA-2020-8bdd3fd7a4",
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/UESGYI5XDAHJBATEZN3MHNDUBDH47AS6/",
                    "x_refsource": "FEDORA"
                },
                {
                    "name": "FEDORA-2020-ea5bdbcc90",
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/A5NSAX4SC3V64PGZUPH7PRDLSON34Q5A/",
                    "x_refsource": "FEDORA"
                },
                {
                    "name": "[debian-lts-announce] 20200715 [SECURITY] [DLA 2280-1] python3.5 security update",
                    "url": "https://lists.debian.org/debian-lts-announce/2020/07/msg00011.html",
                    "x_refsource": "MLIST"
                },
                {
                    "name": "[cassandra-commits] 20210816 [jira] [Created] (CASSANDRA-16857) Security vulnerability CVE-2020-8492",
                    "url": "https://lists.apache.org/thread.html/rdb31a608dd6758c6093fd645aea3fbf022dd25b37109b6aaea5bc0b5@%3Ccommits.cassandra.apache.org%3E",
                    "x_refsource": "MLIST"
                },
                {
                    "name": "[cassandra-commits] 20210816 [jira] [Updated] (CASSANDRA-16857) Security vulnerability CVE-2020-8492",
                    "url": "https://lists.apache.org/thread.html/rfec113c733162b39633fd86a2d0f34bf42ac35f711b3ec1835c774da@%3Ccommits.cassandra.apache.org%3E",
                    "x_refsource": "MLIST"
                }
            ],
            "x_legacyV4Record": {
                "CVE_data_meta": {
                    "ASSIGNER": "cve@mitre.org",
                    "ID": "CVE-2020-8492",
                    "STATE": "PUBLIC"
                },
                "affects": {
                    "vendor": {
                        "vendor_data": [
                            {
                                "product": {
                                    "product_data": [
                                        {
                                            "product_name": "n/a",
                                            "version": {
                                                "version_data": [
                                                    {
                                                        "version_value": "n/a"
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                },
                                "vendor_name": "n/a"
                            }
                        ]
                    }
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "eng",
                            "value": "Python 2.7 through 2.7.17, 3.5 through 3.5.9, 3.6 through 3.6.10, 3.7 through 3.7.6, and 3.8 through 3.8.1 allows an HTTP server to conduct Regular Expression Denial of Service (ReDoS) attacks against a client because of urllib.request.AbstractBasicAuthHandler catastrophic backtracking."
                        }
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "eng",
                                    "value": "n/a"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "https://bugs.python.org/issue39503",
                            "refsource": "MISC",
                            "url": "https://bugs.python.org/issue39503"
                        },
                        {
                            "name": "https://python-security.readthedocs.io/vuln/urllib-basic-auth-regex.html",
                            "refsource": "MISC",
                            "url": "https://python-security.readthedocs.io/vuln/urllib-basic-auth-regex.html"
                        },
                        {
                            "name": "https://github.com/python/cpython/pull/18284",
                            "refsource": "MISC",
                            "url": "https://github.com/python/cpython/pull/18284"
                        },
                        {
                            "name": "https://security.netapp.com/advisory/ntap-20200221-0001/",
                            "refsource": "CONFIRM",
                            "url": "https://security.netapp.com/advisory/ntap-20200221-0001/"
                        },
                        {
                            "name": "openSUSE-SU-2020:0274",
                            "refsource": "SUSE",
                            "url": "http://lists.opensuse.org/opensuse-security-announce/2020-03/msg00003.html"
                        },
                        {
                            "name": "USN-4333-1",
                            "refsource": "UBUNTU",
                            "url": "https://usn.ubuntu.com/4333-1/"
                        },
                        {
                            "name": "USN-4333-2",
                            "refsource": "UBUNTU",
                            "url": "https://usn.ubuntu.com/4333-2/"
                        },
                        {
                            "name": "GLSA-202005-09",
                            "refsource": "GENTOO",
                            "url": "https://security.gentoo.org/glsa/202005-09"
                        },
                        {
                            "name": "FEDORA-2020-98e0f0f11b",
                            "refsource": "FEDORA",
                            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/APGWEMYZIY5VHLCSZ3HD67PA5Z2UQFGH/"
                        },
                        {
                            "name": "FEDORA-2020-6a88dad4a0",
                            "refsource": "FEDORA",
                            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/7WOKDEXLYW5UQ4S7PA7E37IITOC7C56J/"
                        },
                        {
                            "name": "FEDORA-2020-8bdd3fd7a4",
                            "refsource": "FEDORA",
                            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/UESGYI5XDAHJBATEZN3MHNDUBDH47AS6/"
                        },
                        {
                            "name": "FEDORA-2020-ea5bdbcc90",
                            "refsource": "FEDORA",
                            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/A5NSAX4SC3V64PGZUPH7PRDLSON34Q5A/"
                        },
                        {
                            "name": "[debian-lts-announce] 20200715 [SECURITY] [DLA 2280-1] python3.5 security update",
                            "refsource": "MLIST",
                            "url": "https://lists.debian.org/debian-lts-announce/2020/07/msg00011.html"
                        },
                        {
                            "name": "[cassandra-commits] 20210816 [jira] [Created] (CASSANDRA-16857) Security vulnerability CVE-2020-8492",
                            "refsource": "MLIST",
                            "url": "https://lists.apache.org/thread.html/rdb31a608dd6758c6093fd645aea3fbf022dd25b37109b6aaea5bc0b5@%3Ccommits.cassandra.apache.org%3E"
                        },
                        {
                            "name": "[cassandra-commits] 20210816 [jira] [Updated] (CASSANDRA-16857) Security vulnerability CVE-2020-8492",
                            "refsource": "MLIST",
                            "url": "https://lists.apache.org/thread.html/rfec113c733162b39633fd86a2d0f34bf42ac35f711b3ec1835c774da@%3Ccommits.cassandra.apache.org%3E"
                        }
                    ]
                }
            }
        }
    },
    "cveMetadata": {
        "assignerOrgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
        "assignerShortName": "mitre",
        "cveId": "CVE-2020-8492",
        "dateUpdated": "2022-01-27T00:00:00",
        "state": "PUBLISHED"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0"
}