{
    "containers": {
        "cna": {
            "affected": [
                {
                    "product": "n/a",
                    "vendor": "n/a",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "n/a",
                            "versionType": "custom"
                        }
                    ]
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "value": "Zope Object Database (ZODB) before 3.8.2, when certain Zope Enterprise Objects (ZEO) database sharing is enabled, allows remote attackers to bypass authentication via vectors involving the ZEO network protocol."
                }
            ],
            "problemtypes": [
                {
                    "descriptions": [
                        {
                            "description": "n/a",
                            "lang": "en",
                            "type": "text"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2021-12-15",
                "orgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
                "shortName": "mitre"
            },
            "references": [
                {
                    "name": "ADV-2009-2217",
                    "url": "http://www.vupen.com/english/advisories/2009/2217"
                },
                {
                    "name": "36204",
                    "url": "http://secunia.com/advisories/36204"
                },
                {
                    "name": "56826",
                    "url": "http://osvdb.org/56826"
                },
                {
                    "name": "zope-protocol-auth-bypass(52379)",
                    "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/52379"
                },
                {
                    "name": "http://pypi.python.org/pypi/ZODB3/3.8.2#whats-new-in-zodb-3-8-2",
                    "url": "http://pypi.python.org/pypi/ZODB3/3.8.2#whats-new-in-zodb-3-8-2"
                },
                {
                    "name": "36205",
                    "url": "http://secunia.com/advisories/36205"
                },
                {
                    "name": "[zope-announce] 20090806 CVE-2009-0668 and CVE-2009-0669: Releases to fix ZODB ZEO server vulnerabilities",
                    "url": "http://mail.zope.org/pipermail/zope-announce/2009-August/002220.html"
                },
                {
                    "name": "35987",
                    "url": "http://www.securityfocus.com/bid/35987"
                }
            ],
            "x_legacyV4Record": {
                "CVE_data_meta": {
                    "ASSIGNER": "cve@mitre.org",
                    "ID": "CVE-2009-0669",
                    "STATE": "PUBLIC"
                },
                "affects": {
                    "vendor": {
                        "vendor_data": [
                            {
                                "product": {
                                    "product_data": [
                                        {
                                            "product_name": "n/a",
                                            "version": {
                                                "version_data": [
                                                    {
                                                        "version_value": "n/a"
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                },
                                "vendor_name": "n/a"
                            }
                        ]
                    }
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "eng",
                            "value": "Zope Object Database (ZODB) before 3.8.2, when certain Zope Enterprise Objects (ZEO) database sharing is enabled, allows remote attackers to bypass authentication via vectors involving the ZEO network protocol."
                        }
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "eng",
                                    "value": "n/a"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "ADV-2009-2217",
                            "refsource": "VUPEN",
                            "url": "http://www.vupen.com/english/advisories/2009/2217"
                        },
                        {
                            "name": "36204",
                            "refsource": "SECUNIA",
                            "url": "http://secunia.com/advisories/36204"
                        },
                        {
                            "name": "56826",
                            "refsource": "OSVDB",
                            "url": "http://osvdb.org/56826"
                        },
                        {
                            "name": "zope-protocol-auth-bypass(52379)",
                            "refsource": "XF",
                            "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/52379"
                        },
                        {
                            "name": "http://pypi.python.org/pypi/ZODB3/3.8.2#whats-new-in-zodb-3-8-2",
                            "refsource": "CONFIRM",
                            "url": "http://pypi.python.org/pypi/ZODB3/3.8.2#whats-new-in-zodb-3-8-2"
                        },
                        {
                            "name": "36205",
                            "refsource": "SECUNIA",
                            "url": "http://secunia.com/advisories/36205"
                        },
                        {
                            "name": "[zope-announce] 20090806 CVE-2009-0668 and CVE-2009-0669: Releases to fix ZODB ZEO server vulnerabilities",
                            "refsource": "MLIST",
                            "url": "http://mail.zope.org/pipermail/zope-announce/2009-August/002220.html"
                        },
                        {
                            "name": "35987",
                            "refsource": "BID",
                            "url": "http://www.securityfocus.com/bid/35987"
                        }
                    ]
                }
            }
        }
    },
    "cveMetadata": {
        "assignerOrgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
        "assignerShortName": "mitre",
        "cveId": "CVE-2009-0669",
        "dateUpdated": "2021-12-15",
        "state": "PUBLIC"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0"
}