{
    "containers": {
        "cna": {
            "affected": [
                {
                    "product": "n/a",
                    "vendor": "n/a",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "n/a",
                            "versionType": "custom"
                        }
                    ]
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "value": "pam-python before 1.0.7-1 has an issue in regard to the default environment variable handling of Python, which could allow for local root escalation in certain PAM setups."
                }
            ],
            "problemtypes": [
                {
                    "descriptions": [
                        {
                            "description": "n/a",
                            "lang": "en",
                            "type": "text"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2021-12-15",
                "orgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
                "shortName": "mitre"
            },
            "references": [
                {
                    "name": "https://bugzilla.suse.com/show_bug.cgi?id=1150510#c1",
                    "url": "https://bugzilla.suse.com/show_bug.cgi?id=1150510#c1"
                },
                {
                    "name": "https://tracker.debian.org/news/1066790/accepted-pam-python-107-1-source-amd64-all-into-unstable/",
                    "url": "https://tracker.debian.org/news/1066790/accepted-pam-python-107-1-source-amd64-all-into-unstable/"
                },
                {
                    "name": "https://sourceforge.net/p/pam-python/code/ci/0247ab687b4347cc52859ca461fb0126dd7e2ebe/",
                    "url": "https://sourceforge.net/p/pam-python/code/ci/0247ab687b4347cc52859ca461fb0126dd7e2ebe/"
                },
                {
                    "name": "DSA-4555",
                    "url": "https://www.debian.org/security/2019/dsa-4555"
                },
                {
                    "name": "[debian-lts-announce] 20191123 [SECURITY] [DLA 2000-1] pam-python security update",
                    "url": "https://lists.debian.org/debian-lts-announce/2019/11/msg00020.html"
                },
                {
                    "name": "USN-4552-1",
                    "url": "https://usn.ubuntu.com/4552-1/"
                },
                {
                    "name": "USN-4552-2",
                    "url": "https://usn.ubuntu.com/4552-2/"
                }
            ],
            "x_legacyV4Record": {
                "CVE_data_meta": {
                    "ASSIGNER": "cve@mitre.org",
                    "ID": "CVE-2019-16729",
                    "STATE": "PUBLIC"
                },
                "affects": {
                    "vendor": {
                        "vendor_data": [
                            {
                                "product": {
                                    "product_data": [
                                        {
                                            "product_name": "n/a",
                                            "version": {
                                                "version_data": [
                                                    {
                                                        "version_value": "n/a"
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                },
                                "vendor_name": "n/a"
                            }
                        ]
                    }
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "eng",
                            "value": "pam-python before 1.0.7-1 has an issue in regard to the default environment variable handling of Python, which could allow for local root escalation in certain PAM setups."
                        }
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "eng",
                                    "value": "n/a"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "https://bugzilla.suse.com/show_bug.cgi?id=1150510#c1",
                            "refsource": "MISC",
                            "url": "https://bugzilla.suse.com/show_bug.cgi?id=1150510#c1"
                        },
                        {
                            "name": "https://tracker.debian.org/news/1066790/accepted-pam-python-107-1-source-amd64-all-into-unstable/",
                            "refsource": "MISC",
                            "url": "https://tracker.debian.org/news/1066790/accepted-pam-python-107-1-source-amd64-all-into-unstable/"
                        },
                        {
                            "name": "https://sourceforge.net/p/pam-python/code/ci/0247ab687b4347cc52859ca461fb0126dd7e2ebe/",
                            "refsource": "MISC",
                            "url": "https://sourceforge.net/p/pam-python/code/ci/0247ab687b4347cc52859ca461fb0126dd7e2ebe/"
                        },
                        {
                            "name": "DSA-4555",
                            "refsource": "DEBIAN",
                            "url": "https://www.debian.org/security/2019/dsa-4555"
                        },
                        {
                            "name": "[debian-lts-announce] 20191123 [SECURITY] [DLA 2000-1] pam-python security update",
                            "refsource": "MLIST",
                            "url": "https://lists.debian.org/debian-lts-announce/2019/11/msg00020.html"
                        },
                        {
                            "name": "USN-4552-1",
                            "refsource": "UBUNTU",
                            "url": "https://usn.ubuntu.com/4552-1/"
                        },
                        {
                            "name": "USN-4552-2",
                            "refsource": "UBUNTU",
                            "url": "https://usn.ubuntu.com/4552-2/"
                        }
                    ]
                }
            }
        }
    },
    "cveMetadata": {
        "assignerOrgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
        "assignerShortName": "mitre",
        "cveId": "CVE-2019-16729",
        "dateUpdated": "2021-12-15",
        "state": "PUBLIC"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0"
}