{
    "containers": {
        "cna": {
            "affected": [
                {
                    "defaultStatus": "unknown",
                    "product": "kernel",
                    "vendor": "The Linux Foundation",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "from v4.16 and newer"
                        }
                    ]
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "value": "A flaw was found in the Linux kernel's handle_rx() function in the [vhost_net] driver. A malicious virtual guest, under specific conditions, can trigger an out-of-bounds write in a kmalloc-8 slab on a virtual host which may lead to a kernel memory corruption and a system panic. Due to the nature of the flaw, privilege escalation cannot be fully ruled out. Versions from v4.16 and newer are vulnerable."
                }
            ],
            "metrics": [
                {
                    "cvssV3_0": {
                        "vectorString": "5.9/CVSS:3.0/AV:A/AC:H/PR:N/UI:N/S:U/C:H/I:L/A:N",
                        "version": "3.0"
                    }
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "cweId": "CWE-787",
                            "description": "CWE-787",
                            "lang": "en",
                            "type": "CWE"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2022-01-12T00:00:00",
                "orgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
                "shortName": "redhat"
            },
            "references": [
                {
                    "name": "USN-3903-2",
                    "url": "https://usn.ubuntu.com/3903-2/",
                    "x_refsource": "UBUNTU"
                },
                {
                    "name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-16880",
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-16880",
                    "x_refsource": "CONFIRM"
                },
                {
                    "name": "106735",
                    "url": "http://www.securityfocus.com/bid/106735",
                    "x_refsource": "BID"
                },
                {
                    "name": "USN-3903-1",
                    "url": "https://usn.ubuntu.com/3903-1/",
                    "x_refsource": "UBUNTU"
                },
                {
                    "name": "https://support.f5.com/csp/article/K03593314",
                    "url": "https://support.f5.com/csp/article/K03593314",
                    "x_refsource": "CONFIRM"
                },
                {
                    "name": "openSUSE-SU-2019:1404",
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2019-05/msg00037.html",
                    "x_refsource": "SUSE"
                }
            ],
            "x_legacyV4Record": {
                "CVE_data_meta": {
                    "ASSIGNER": "secalert@redhat.com",
                    "ID": "CVE-2018-16880",
                    "STATE": "PUBLIC"
                },
                "affects": {
                    "vendor": {
                        "vendor_data": [
                            {
                                "product": {
                                    "product_data": [
                                        {
                                            "product_name": "kernel",
                                            "version": {
                                                "version_data": [
                                                    {
                                                        "version_value": "from v4.16 and newer"
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                },
                                "vendor_name": "The Linux Foundation"
                            }
                        ]
                    }
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "eng",
                            "value": "A flaw was found in the Linux kernel's handle_rx() function in the [vhost_net] driver. A malicious virtual guest, under specific conditions, can trigger an out-of-bounds write in a kmalloc-8 slab on a virtual host which may lead to a kernel memory corruption and a system panic. Due to the nature of the flaw, privilege escalation cannot be fully ruled out. Versions from v4.16 and newer are vulnerable."
                        }
                    ]
                },
                "impact": {
                    "cvss": [
                        [
                            {
                                "vectorString": "5.9/CVSS:3.0/AV:A/AC:H/PR:N/UI:N/S:U/C:H/I:L/A:N",
                                "version": "3.0"
                            }
                        ]
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "eng",
                                    "value": "CWE-787"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "USN-3903-2",
                            "refsource": "UBUNTU",
                            "url": "https://usn.ubuntu.com/3903-2/"
                        },
                        {
                            "name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-16880",
                            "refsource": "CONFIRM",
                            "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-16880"
                        },
                        {
                            "name": "106735",
                            "refsource": "BID",
                            "url": "http://www.securityfocus.com/bid/106735"
                        },
                        {
                            "name": "USN-3903-1",
                            "refsource": "UBUNTU",
                            "url": "https://usn.ubuntu.com/3903-1/"
                        },
                        {
                            "name": "https://support.f5.com/csp/article/K03593314",
                            "refsource": "CONFIRM",
                            "url": "https://support.f5.com/csp/article/K03593314"
                        },
                        {
                            "name": "openSUSE-SU-2019:1404",
                            "refsource": "SUSE",
                            "url": "http://lists.opensuse.org/opensuse-security-announce/2019-05/msg00037.html"
                        }
                    ]
                }
            }
        }
    },
    "cveMetadata": {
        "assignerOrgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
        "assignerShortName": "redhat",
        "cveId": "CVE-2018-16880",
        "dateUpdated": "2022-01-12T00:00:00",
        "state": "PUBLISHED"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0",
    "x_ValidationErrors": [
        "$ -- validator = oneOf"
    ]
}