{
    "containers": {
        "cna": {
            "affected": [
                {
                    "defaultStatus": "unknown",
                    "product": "n/a",
                    "vendor": "n/a",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "n/a"
                        }
                    ]
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "value": "Algorithmic complexity vulnerability in the forms library in Django 1.0 before 1.0.4 and 1.1 before 1.1.1 allows remote attackers to cause a denial of service (CPU consumption) via a crafted (1) EmailField (email address) or (2) URLField (URL) that triggers a large amount of backtracking in a regular expression."
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "description": "n/a",
                            "lang": "en",
                            "type": "text"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2022-01-12T00:00:00",
                "orgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
                "shortName": "mitre"
            },
            "references": [
                {
                    "name": "36655",
                    "url": "http://www.securityfocus.com/bid/36655",
                    "x_refsource": "BID"
                },
                {
                    "name": "django-emailfield-urlfield-dos(53727)",
                    "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/53727",
                    "x_refsource": "XF"
                },
                {
                    "name": "http://www.djangoproject.com/weblog/2009/oct/09/security/",
                    "url": "http://www.djangoproject.com/weblog/2009/oct/09/security/",
                    "x_refsource": "CONFIRM"
                },
                {
                    "name": "36948",
                    "url": "http://secunia.com/advisories/36948",
                    "x_refsource": "SECUNIA"
                },
                {
                    "name": "36968",
                    "url": "http://secunia.com/advisories/36968",
                    "x_refsource": "SECUNIA"
                },
                {
                    "name": "DSA-1905",
                    "url": "http://www.debian.org/security/2009/dsa-1905",
                    "x_refsource": "DEBIAN"
                },
                {
                    "name": "http://groups.google.com/group/django-users/browse_thread/thread/15df9e45118dfc51/",
                    "url": "http://groups.google.com/group/django-users/browse_thread/thread/15df9e45118dfc51/",
                    "x_refsource": "MISC"
                },
                {
                    "name": "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=550457",
                    "url": "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=550457",
                    "x_refsource": "CONFIRM"
                },
                {
                    "name": "[oss-security] 20091013 Re: Duplicate CVE assignment notification [was: CVE id request: django]",
                    "url": "http://www.openwall.com/lists/oss-security/2009/10/13/6",
                    "x_refsource": "MLIST"
                },
                {
                    "name": "ADV-2009-2871",
                    "url": "http://www.vupen.com/english/advisories/2009/2871",
                    "x_refsource": "VUPEN"
                }
            ],
            "x_legacyV4Record": {
                "CVE_data_meta": {
                    "ASSIGNER": "cve@mitre.org",
                    "ID": "CVE-2009-3695",
                    "STATE": "PUBLIC"
                },
                "affects": {
                    "vendor": {
                        "vendor_data": [
                            {
                                "product": {
                                    "product_data": [
                                        {
                                            "product_name": "n/a",
                                            "version": {
                                                "version_data": [
                                                    {
                                                        "version_value": "n/a"
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                },
                                "vendor_name": "n/a"
                            }
                        ]
                    }
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "eng",
                            "value": "Algorithmic complexity vulnerability in the forms library in Django 1.0 before 1.0.4 and 1.1 before 1.1.1 allows remote attackers to cause a denial of service (CPU consumption) via a crafted (1) EmailField (email address) or (2) URLField (URL) that triggers a large amount of backtracking in a regular expression."
                        }
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "eng",
                                    "value": "n/a"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "36655",
                            "refsource": "BID",
                            "url": "http://www.securityfocus.com/bid/36655"
                        },
                        {
                            "name": "django-emailfield-urlfield-dos(53727)",
                            "refsource": "XF",
                            "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/53727"
                        },
                        {
                            "name": "http://www.djangoproject.com/weblog/2009/oct/09/security/",
                            "refsource": "CONFIRM",
                            "url": "http://www.djangoproject.com/weblog/2009/oct/09/security/"
                        },
                        {
                            "name": "36948",
                            "refsource": "SECUNIA",
                            "url": "http://secunia.com/advisories/36948"
                        },
                        {
                            "name": "36968",
                            "refsource": "SECUNIA",
                            "url": "http://secunia.com/advisories/36968"
                        },
                        {
                            "name": "DSA-1905",
                            "refsource": "DEBIAN",
                            "url": "http://www.debian.org/security/2009/dsa-1905"
                        },
                        {
                            "name": "http://groups.google.com/group/django-users/browse_thread/thread/15df9e45118dfc51/",
                            "refsource": "MISC",
                            "url": "http://groups.google.com/group/django-users/browse_thread/thread/15df9e45118dfc51/"
                        },
                        {
                            "name": "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=550457",
                            "refsource": "CONFIRM",
                            "url": "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=550457"
                        },
                        {
                            "name": "[oss-security] 20091013 Re: Duplicate CVE assignment notification [was: CVE id request: django]",
                            "refsource": "MLIST",
                            "url": "http://www.openwall.com/lists/oss-security/2009/10/13/6"
                        },
                        {
                            "name": "ADV-2009-2871",
                            "refsource": "VUPEN",
                            "url": "http://www.vupen.com/english/advisories/2009/2871"
                        }
                    ]
                }
            }
        }
    },
    "cveMetadata": {
        "assignerOrgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
        "assignerShortName": "mitre",
        "cveId": "CVE-2009-3695",
        "dateUpdated": "2022-01-12T00:00:00",
        "state": "PUBLISHED"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0"
}