{
    "containers": {
        "cna": {
            "affected": [
                {
                    "defaultStatus": "unknown",
                    "product": "n/a",
                    "vendor": "n/a",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "n/a"
                        }
                    ]
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "value": "An issue was discovered in Django 2.2 before 2.2.16, 3.0 before 3.0.10, and 3.1 before 3.1.1 (when Python 3.7+ is used). The intermediate-level directories of the filesystem cache had the system's standard umask rather than 0o077."
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "description": "n/a",
                            "lang": "en",
                            "type": "text"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2022-01-13T00:00:00",
                "orgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
                "shortName": "mitre"
            },
            "references": [
                {
                    "name": "https://docs.djangoproject.com/en/dev/releases/security/",
                    "url": "https://docs.djangoproject.com/en/dev/releases/security/",
                    "x_refsource": "MISC"
                },
                {
                    "name": "USN-4479-1",
                    "url": "https://usn.ubuntu.com/4479-1/",
                    "x_refsource": "UBUNTU"
                },
                {
                    "name": "FEDORA-2020-94407454d7",
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/F2ZHO3GZCJMP3DDTXCNVFV6ED3W64NAU/",
                    "x_refsource": "FEDORA"
                },
                {
                    "name": "FEDORA-2020-6941c0a65b",
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZCRPQCBTV3RZHKVZ6K6QOAANPRZQD3GI/",
                    "x_refsource": "FEDORA"
                },
                {
                    "name": "FEDORA-2020-9c6b391162",
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/OLGFFLMF3X6USMJD7V5F5P4K2WVUTO3T/",
                    "x_refsource": "FEDORA"
                },
                {
                    "name": "https://www.oracle.com/security-alerts/cpujan2021.html",
                    "url": "https://www.oracle.com/security-alerts/cpujan2021.html",
                    "x_refsource": "MISC"
                },
                {
                    "name": "https://groups.google.com/forum/#!topic/django-announce/zFCMdgUnutU",
                    "url": "https://groups.google.com/forum/#!topic/django-announce/zFCMdgUnutU",
                    "x_refsource": "MISC"
                },
                {
                    "name": "https://groups.google.com/forum/#!topic/django-announce/Gdqn58RqIDM",
                    "url": "https://groups.google.com/forum/#!topic/django-announce/Gdqn58RqIDM",
                    "x_refsource": "MISC"
                },
                {
                    "name": "https://www.openwall.com/lists/oss-security/2020/09/01/2",
                    "url": "https://www.openwall.com/lists/oss-security/2020/09/01/2",
                    "x_refsource": "MISC"
                },
                {
                    "name": "https://www.djangoproject.com/weblog/2020/sep/01/security-releases/",
                    "url": "https://www.djangoproject.com/weblog/2020/sep/01/security-releases/",
                    "x_refsource": "MISC"
                },
                {
                    "name": "https://security.netapp.com/advisory/ntap-20200918-0004/",
                    "url": "https://security.netapp.com/advisory/ntap-20200918-0004/",
                    "x_refsource": "CONFIRM"
                }
            ],
            "x_legacyV4Record": {
                "CVE_data_meta": {
                    "ASSIGNER": "cve@mitre.org",
                    "ID": "CVE-2020-24584",
                    "STATE": "PUBLIC"
                },
                "affects": {
                    "vendor": {
                        "vendor_data": [
                            {
                                "product": {
                                    "product_data": [
                                        {
                                            "product_name": "n/a",
                                            "version": {
                                                "version_data": [
                                                    {
                                                        "version_value": "n/a"
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                },
                                "vendor_name": "n/a"
                            }
                        ]
                    }
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "eng",
                            "value": "An issue was discovered in Django 2.2 before 2.2.16, 3.0 before 3.0.10, and 3.1 before 3.1.1 (when Python 3.7+ is used). The intermediate-level directories of the filesystem cache had the system's standard umask rather than 0o077."
                        }
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "eng",
                                    "value": "n/a"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "https://docs.djangoproject.com/en/dev/releases/security/",
                            "refsource": "MISC",
                            "url": "https://docs.djangoproject.com/en/dev/releases/security/"
                        },
                        {
                            "name": "USN-4479-1",
                            "refsource": "UBUNTU",
                            "url": "https://usn.ubuntu.com/4479-1/"
                        },
                        {
                            "name": "FEDORA-2020-94407454d7",
                            "refsource": "FEDORA",
                            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/F2ZHO3GZCJMP3DDTXCNVFV6ED3W64NAU/"
                        },
                        {
                            "name": "FEDORA-2020-6941c0a65b",
                            "refsource": "FEDORA",
                            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZCRPQCBTV3RZHKVZ6K6QOAANPRZQD3GI/"
                        },
                        {
                            "name": "FEDORA-2020-9c6b391162",
                            "refsource": "FEDORA",
                            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/OLGFFLMF3X6USMJD7V5F5P4K2WVUTO3T/"
                        },
                        {
                            "name": "https://www.oracle.com/security-alerts/cpujan2021.html",
                            "refsource": "MISC",
                            "url": "https://www.oracle.com/security-alerts/cpujan2021.html"
                        },
                        {
                            "name": "https://groups.google.com/forum/#!topic/django-announce/zFCMdgUnutU",
                            "refsource": "MISC",
                            "url": "https://groups.google.com/forum/#!topic/django-announce/zFCMdgUnutU"
                        },
                        {
                            "name": "https://groups.google.com/forum/#!topic/django-announce/Gdqn58RqIDM",
                            "refsource": "MISC",
                            "url": "https://groups.google.com/forum/#!topic/django-announce/Gdqn58RqIDM"
                        },
                        {
                            "name": "https://www.openwall.com/lists/oss-security/2020/09/01/2",
                            "refsource": "MISC",
                            "url": "https://www.openwall.com/lists/oss-security/2020/09/01/2"
                        },
                        {
                            "name": "https://www.djangoproject.com/weblog/2020/sep/01/security-releases/",
                            "refsource": "MISC",
                            "url": "https://www.djangoproject.com/weblog/2020/sep/01/security-releases/"
                        },
                        {
                            "name": "https://security.netapp.com/advisory/ntap-20200918-0004/",
                            "refsource": "CONFIRM",
                            "url": "https://security.netapp.com/advisory/ntap-20200918-0004/"
                        }
                    ]
                }
            }
        }
    },
    "cveMetadata": {
        "assignerOrgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
        "assignerShortName": "mitre",
        "cveId": "CVE-2020-24584",
        "dateUpdated": "2022-01-13T00:00:00",
        "state": "PUBLISHED"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0"
}