{
    "containers": {
        "cna": {
            "affected": [
                {
                    "defaultStatus": "unknown",
                    "product": "n/a",
                    "vendor": "n/a",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "n/a"
                        }
                    ]
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "value": "http.client in Python 3.x before 3.5.10, 3.6.x before 3.6.12, 3.7.x before 3.7.9, and 3.8.x before 3.8.5 allows CRLF injection if the attacker controls the HTTP request method, as demonstrated by inserting CR and LF control characters in the first argument of HTTPConnection.request."
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "description": "n/a",
                            "lang": "en",
                            "type": "text"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2022-01-13T00:00:00",
                "orgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
                "shortName": "mitre"
            },
            "references": [
                {
                    "name": "https://python-security.readthedocs.io/vuln/http-header-injection-method.html",
                    "url": "https://python-security.readthedocs.io/vuln/http-header-injection-method.html",
                    "x_refsource": "MISC"
                },
                {
                    "name": "https://bugs.python.org/issue39603",
                    "url": "https://bugs.python.org/issue39603",
                    "x_refsource": "MISC"
                },
                {
                    "name": "FEDORA-2020-221823ebdd",
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/BW4GCLQISJCOEGQNIMVUZDQMIY6RR6CC/",
                    "x_refsource": "FEDORA"
                },
                {
                    "name": "FEDORA-2020-887d3fa26f",
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JWMAVY4T4257AZHTF2RZJKNJNSJFY24O/",
                    "x_refsource": "FEDORA"
                },
                {
                    "name": "FEDORA-2020-d30881c970",
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/OXI72HIHMXCQFWTULUXDG7VDA2BCYL4Y/",
                    "x_refsource": "FEDORA"
                },
                {
                    "name": "USN-4581-1",
                    "url": "https://usn.ubuntu.com/4581-1/",
                    "x_refsource": "UBUNTU"
                },
                {
                    "name": "FEDORA-2020-e33acdea18",
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HDQ2THWU4GPV4Y5H5WW5PFMSWXL2CRFD/",
                    "x_refsource": "FEDORA"
                },
                {
                    "name": "openSUSE-SU-2020:1859",
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2020-11/msg00027.html",
                    "x_refsource": "SUSE"
                },
                {
                    "name": "FEDORA-2020-d42cb01973",
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QOX7DGMMWWL6POCRYGAUCISOLR2IG3XV/",
                    "x_refsource": "FEDORA"
                },
                {
                    "name": "[debian-lts-announce] 20201119 [SECURITY] [DLA 2456-1] python3.5 security update",
                    "url": "https://lists.debian.org/debian-lts-announce/2020/11/msg00032.html",
                    "x_refsource": "MLIST"
                },
                {
                    "name": "GLSA-202101-18",
                    "url": "https://security.gentoo.org/glsa/202101-18",
                    "x_refsource": "GENTOO"
                },
                {
                    "name": "https://www.oracle.com/security-alerts/cpuoct2021.html",
                    "url": "https://www.oracle.com/security-alerts/cpuoct2021.html",
                    "x_refsource": "MISC"
                },
                {
                    "name": "https://security.netapp.com/advisory/ntap-20201023-0001/",
                    "url": "https://security.netapp.com/advisory/ntap-20201023-0001/",
                    "x_refsource": "CONFIRM"
                }
            ],
            "x_legacyV4Record": {
                "CVE_data_meta": {
                    "ASSIGNER": "cve@mitre.org",
                    "ID": "CVE-2020-26116",
                    "STATE": "PUBLIC"
                },
                "affects": {
                    "vendor": {
                        "vendor_data": [
                            {
                                "product": {
                                    "product_data": [
                                        {
                                            "product_name": "n/a",
                                            "version": {
                                                "version_data": [
                                                    {
                                                        "version_value": "n/a"
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                },
                                "vendor_name": "n/a"
                            }
                        ]
                    }
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "eng",
                            "value": "http.client in Python 3.x before 3.5.10, 3.6.x before 3.6.12, 3.7.x before 3.7.9, and 3.8.x before 3.8.5 allows CRLF injection if the attacker controls the HTTP request method, as demonstrated by inserting CR and LF control characters in the first argument of HTTPConnection.request."
                        }
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "eng",
                                    "value": "n/a"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "https://python-security.readthedocs.io/vuln/http-header-injection-method.html",
                            "refsource": "MISC",
                            "url": "https://python-security.readthedocs.io/vuln/http-header-injection-method.html"
                        },
                        {
                            "name": "https://bugs.python.org/issue39603",
                            "refsource": "MISC",
                            "url": "https://bugs.python.org/issue39603"
                        },
                        {
                            "name": "FEDORA-2020-221823ebdd",
                            "refsource": "FEDORA",
                            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/BW4GCLQISJCOEGQNIMVUZDQMIY6RR6CC/"
                        },
                        {
                            "name": "FEDORA-2020-887d3fa26f",
                            "refsource": "FEDORA",
                            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JWMAVY4T4257AZHTF2RZJKNJNSJFY24O/"
                        },
                        {
                            "name": "FEDORA-2020-d30881c970",
                            "refsource": "FEDORA",
                            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/OXI72HIHMXCQFWTULUXDG7VDA2BCYL4Y/"
                        },
                        {
                            "name": "USN-4581-1",
                            "refsource": "UBUNTU",
                            "url": "https://usn.ubuntu.com/4581-1/"
                        },
                        {
                            "name": "FEDORA-2020-e33acdea18",
                            "refsource": "FEDORA",
                            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HDQ2THWU4GPV4Y5H5WW5PFMSWXL2CRFD/"
                        },
                        {
                            "name": "openSUSE-SU-2020:1859",
                            "refsource": "SUSE",
                            "url": "http://lists.opensuse.org/opensuse-security-announce/2020-11/msg00027.html"
                        },
                        {
                            "name": "FEDORA-2020-d42cb01973",
                            "refsource": "FEDORA",
                            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QOX7DGMMWWL6POCRYGAUCISOLR2IG3XV/"
                        },
                        {
                            "name": "[debian-lts-announce] 20201119 [SECURITY] [DLA 2456-1] python3.5 security update",
                            "refsource": "MLIST",
                            "url": "https://lists.debian.org/debian-lts-announce/2020/11/msg00032.html"
                        },
                        {
                            "name": "GLSA-202101-18",
                            "refsource": "GENTOO",
                            "url": "https://security.gentoo.org/glsa/202101-18"
                        },
                        {
                            "name": "https://www.oracle.com/security-alerts/cpuoct2021.html",
                            "refsource": "MISC",
                            "url": "https://www.oracle.com/security-alerts/cpuoct2021.html"
                        },
                        {
                            "name": "https://security.netapp.com/advisory/ntap-20201023-0001/",
                            "refsource": "CONFIRM",
                            "url": "https://security.netapp.com/advisory/ntap-20201023-0001/"
                        }
                    ]
                }
            }
        }
    },
    "cveMetadata": {
        "assignerOrgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
        "assignerShortName": "mitre",
        "cveId": "CVE-2020-26116",
        "dateUpdated": "2022-01-13T00:00:00",
        "state": "PUBLISHED"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0"
}