{
    "containers": {
        "cna": {
            "affected": [
                {
                    "product": "n/a",
                    "vendor": "n/a",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "n/a",
                            "versionType": "custom"
                        }
                    ]
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "value": "In the Linux kernel 4.13 through 4.16.11, ext4_read_inline_data() in fs/ext4/inline.c performs a memcpy with an untrusted length value in certain circumstances involving a crafted filesystem that stores the system.data extended attribute value in a dedicated inode."
                }
            ],
            "problemtypes": [
                {
                    "descriptions": [
                        {
                            "description": "n/a",
                            "lang": "en",
                            "type": "text"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2021-12-15",
                "orgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
                "shortName": "mitre"
            },
            "references": [
                {
                    "name": "USN-3752-2",
                    "url": "https://usn.ubuntu.com/3752-2/"
                },
                {
                    "name": "104291",
                    "url": "http://www.securityfocus.com/bid/104291"
                },
                {
                    "name": "https://bugs.chromium.org/p/project-zero/issues/detail?id=1580",
                    "url": "https://bugs.chromium.org/p/project-zero/issues/detail?id=1580"
                },
                {
                    "name": "USN-3752-3",
                    "url": "https://usn.ubuntu.com/3752-3/"
                },
                {
                    "name": "https://bugzilla.kernel.org/show_bug.cgi?id=199803",
                    "url": "https://bugzilla.kernel.org/show_bug.cgi?id=199803"
                },
                {
                    "name": "44832",
                    "url": "https://www.exploit-db.com/exploits/44832/"
                },
                {
                    "name": "RHSA-2019:0525",
                    "url": "https://access.redhat.com/errata/RHSA-2019:0525"
                },
                {
                    "name": "USN-3752-1",
                    "url": "https://usn.ubuntu.com/3752-1/"
                }
            ],
            "x_legacyV4Record": {
                "CVE_data_meta": {
                    "ASSIGNER": "cve@mitre.org",
                    "ID": "CVE-2018-11412",
                    "STATE": "PUBLIC"
                },
                "affects": {
                    "vendor": {
                        "vendor_data": [
                            {
                                "product": {
                                    "product_data": [
                                        {
                                            "product_name": "n/a",
                                            "version": {
                                                "version_data": [
                                                    {
                                                        "version_value": "n/a"
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                },
                                "vendor_name": "n/a"
                            }
                        ]
                    }
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "eng",
                            "value": "In the Linux kernel 4.13 through 4.16.11, ext4_read_inline_data() in fs/ext4/inline.c performs a memcpy with an untrusted length value in certain circumstances involving a crafted filesystem that stores the system.data extended attribute value in a dedicated inode."
                        }
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "eng",
                                    "value": "n/a"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "USN-3752-2",
                            "refsource": "UBUNTU",
                            "url": "https://usn.ubuntu.com/3752-2/"
                        },
                        {
                            "name": "104291",
                            "refsource": "BID",
                            "url": "http://www.securityfocus.com/bid/104291"
                        },
                        {
                            "name": "https://bugs.chromium.org/p/project-zero/issues/detail?id=1580",
                            "refsource": "MISC",
                            "url": "https://bugs.chromium.org/p/project-zero/issues/detail?id=1580"
                        },
                        {
                            "name": "USN-3752-3",
                            "refsource": "UBUNTU",
                            "url": "https://usn.ubuntu.com/3752-3/"
                        },
                        {
                            "name": "https://bugzilla.kernel.org/show_bug.cgi?id=199803",
                            "refsource": "MISC",
                            "url": "https://bugzilla.kernel.org/show_bug.cgi?id=199803"
                        },
                        {
                            "name": "44832",
                            "refsource": "EXPLOIT-DB",
                            "url": "https://www.exploit-db.com/exploits/44832/"
                        },
                        {
                            "name": "RHSA-2019:0525",
                            "refsource": "REDHAT",
                            "url": "https://access.redhat.com/errata/RHSA-2019:0525"
                        },
                        {
                            "name": "USN-3752-1",
                            "refsource": "UBUNTU",
                            "url": "https://usn.ubuntu.com/3752-1/"
                        }
                    ]
                }
            }
        }
    },
    "cveMetadata": {
        "assignerOrgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
        "assignerShortName": "mitre",
        "cveId": "CVE-2018-11412",
        "dateUpdated": "2021-12-15",
        "state": "PUBLIC"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0"
}